### ISSUE TITLE
hello i try to compile the code but it does not work

### ISSUE THREAD

**Issue by hooijschuur** [Kolkman/ESPressoMachine#1]
i use mrcode (vscode & platformio) on linux.
can you give me a hint to fix this

Thanks in advance 

make: *** No rule to make target 'WEBSources/index.html', needed by 'include/pages/index.html.h'.  Stop.
OSError: 'make' exited 2:
  File "/home/marchooijschuur/.platformio/penv/lib/python3.10/site-packages/platformio/builder/main.py", line 173:
    env.SConscript("$BUILD_SCRIPT")
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/marchooijschuur/.platformio/platforms/espressif32/builder/main.py", line 346:
    target_elf = env.BuildProgram()
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/home/marchooijschuur/.platformio/penv/lib/python3.10/site-packages/platformio/builder/tools/piobuild.py", line 61:
    env.ProcessProgramDeps()
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/home/marchooijschuur/.platformio/penv/lib/python3.10/site-packages/platformio/builder/tools/piobuild.py", line 118:
    env.ProcessFlags(env.get("BUILD_FLAGS"))
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/home/marchooijschuur/.platformio/penv/lib/python3.10/site-packages/platformio/builder/tools/piobuild.py", line 228:
    env.Append(**env.ParseFlagsExtended(flags))
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/home/marchooijschuur/.platformio/penv/lib/python3.10/site-packages/platformio/builder/tools/piobuild.py", line 190:
    for key, value in env.ParseFlags(str(raw)).items():
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Environment.py", line 1035:
    do_parse(arg)
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Environment.py", line 887:
    arg = self.backtick(arg[1:])
  File "/home/marchooijschuur/.platformio/packages/tool-scons/scons-local-4.5.2/SCons/Environment.py", line 798:
    raise OSError("'%s' exited %d" % (command, status))
========================== [FAILED] Took 0.30 seconds =========

**Comment by Kolkman** [comment]
When you checkout the git repository 'WEBSources/index.html should be included, it looks like it is missing. Perhaps you accidentally removed it?

 A quick fix would be  to copy it into place from https://github.com/Kolkman/ESP32ressoMachine/blob/main/WEBsources/index.html


Good luck,

—Olaf

**Comment by hooijschuur** [comment]
thank you for the quick response.

i hoped it was that easy but index.html is on its place.
i cannot find include/pages/index.html.h
also not in your repository
downloaded a fresh one from github compiled without modification and i get
the same error.
is it possible that it has to do with the operating system.


Op di 28 nov 2023 om 21:57 schreef Olaf ***@***.***>:

>
>
> When you checkout the git repository 'WEBSources/index.html should be
> included, it looks like it is missing. Perhaps you accidentally removed it?
>
> A quick fix would be to copy it into place from
> https://github.com/Kolkman/ESP32ressoMachine/blob/main/WEBsources/index.html
>
>
> Good luck,
>
> —Olaf
>

**Comment by Kolkman** [comment]
Have you installed the minifyAll extension in visual studio?marketplace.visualstudio.com-----Composed on a mobile device, with clumsy thumbs and unpredictable autocorrect.On 28 Nov 2023, at 22:34, hooijschuur ***@***.***> wrote:﻿
thank you for the quick response.



i hoped it was that easy but index.html is on its place.

i cannot find include/pages/index.html.h

also not in your repository

downloaded a fresh one from github compiled without modification and i get

the same error.

is it possible that it has to do with the operating system.





Op di 28 nov 2023 om 21:57 schreef Olaf ***@***.***>:



>

>

> When you checkout the git repository 'WEBSources/index.html should be

> included, it looks like it is missing. Perhaps you accidentally removed it?

>

> A quick fix would be to copy it into place from

> https://github.com/Kolkman/ESP32ressoMachine/blob/main/WEBsources/index.html

>

>

> Good luck,

>

> —Olaf

>

**Comment by hooijschuur** [comment]
minifyall was installed ,tried to compile in windows and tried a fresh vscode&platformio with no luck.

used the latest version without any alteration.

**Comment by Kolkman** [comment]
> i cannot find include/pages/index.html.h
That file is produced by ProduceDefine.py which is called through a makefile. Since it is a result of the build process I have not added it to git hub.

From this part of the error log:
```
make: *** No rule to make target 'WEBSources/index.html', needed by 'include/pages/index.html.h'. Stop.
OSError: 'make' exited 2:
```
it looks like `make` cannot find `WEBSources/index.html` from the path that the make command is executed. 
Have you tried to run `make` from the vstudio terminal?

**Comment by hooijschuur** [comment]
i use make -d all and removed looking for rules lines at .......

make -d all
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Updating makefiles....
 Considering target file 'Makefile'.
  Looking for an implicit rule for 'Makefile'.
  Trying pattern rule with stem 'Makefile'.
.........

No implicit rule found for 'Makefile'.
  Finished prerequisites of target file 'Makefile'.
 No need to remake target 'Makefile'.
Updating goal targets....
Considering target file 'all'.
 File 'all' does not exist.
  Considering target file 'include/pages/index.html.h'.
   File 'include/pages/index.html.h' does not exist.
    Considering target file 'WEBSources/index.html'.
     File 'WEBSources/index.html' does not exist.
     Looking for an implicit rule for 'WEBSources/index.html'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.o'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.c'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.cc'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.C'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.cpp'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.p'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.f'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.F'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.m'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.r'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.s'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.S'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.mod'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.sh'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html,v'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/RCS/index.html,v'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/RCS/index.html'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/s.index.html'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/SCCS/s.index.html'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.o'.
     Looking for a rule with intermediate file 'WEBSources/index.html.o'.
      Avoiding implicit rule recursion.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.c'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.cc'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.C'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.cpp'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.p'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.f'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.F'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.m'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.r'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.s'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.S'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.mod'.
      Trying pattern rule with stem 'index.html.o'.
      Trying implicit prerequisite 'WEBSources/index.html.o,v'.
      Trying pattern rule with stem 'index.html.o'.
      Trying implicit prerequisite 'WEBSources/RCS/index.html.o,v'.
      Trying pattern rule with stem 'index.html.o'.
      Trying implicit prerequisite 'WEBSources/RCS/index.html.o'.
      Trying pattern rule with stem 'index.html.o'.
      Trying implicit prerequisite 'WEBSources/s.index.html.o'.
      Trying pattern rule with stem 'index.html.o'.
      Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.o'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.c'.
      Looking for a rule with intermediate file 'WEBSources/index.html.c'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.y'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.l'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.w'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.w'.
       Trying pattern rule with stem 'index.html.c'.
       Trying implicit prerequisite 'WEBSources/index.html.c,v'.
       Trying pattern rule with stem 'index.html.c'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.c,v'.
       Trying pattern rule with stem 'index.html.c'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.c'.
       Trying pattern rule with stem 'index.html.c'.
       Trying implicit prerequisite 'WEBSources/s.index.html.c'.
       Trying pattern rule with stem 'index.html.c'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.c'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.y'.
       Looking for a rule with intermediate file 'WEBSources/index.html.y'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html.y'.
        Trying implicit prerequisite 'WEBSources/index.html.y,v'.
        Trying pattern rule with stem 'index.html.y'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.y,v'.
        Trying pattern rule with stem 'index.html.y'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.y'.
        Trying pattern rule with stem 'index.html.y'.
        Trying implicit prerequisite 'WEBSources/s.index.html.y'.
        Trying pattern rule with stem 'index.html.y'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.y'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.l'.
       Looking for a rule with intermediate file 'WEBSources/index.html.l'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html.l'.
        Trying implicit prerequisite 'WEBSources/index.html.l,v'.
        Trying pattern rule with stem 'index.html.l'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.l,v'.
        Trying pattern rule with stem 'index.html.l'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.l'.
        Trying pattern rule with stem 'index.html.l'.
        Trying implicit prerequisite 'WEBSources/s.index.html.l'.
        Trying pattern rule with stem 'index.html.l'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.l'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.w'.
       Looking for a rule with intermediate file 'WEBSources/index.html.w'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html.w'.
        Trying implicit prerequisite 'WEBSources/index.html.w,v'.
        Trying pattern rule with stem 'index.html.w'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.w,v'.
        Trying pattern rule with stem 'index.html.w'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.w'.
        Trying pattern rule with stem 'index.html.w'.
        Trying implicit prerequisite 'WEBSources/s.index.html.w'.
        Trying pattern rule with stem 'index.html.w'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.w'.
       Trying pattern rule with stem 'index.html'.
       Rejecting impossible implicit prerequisite 'WEBSources/index.html.w'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.cc'.
      Looking for a rule with intermediate file 'WEBSources/index.html.cc'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html.cc'.
       Trying implicit prerequisite 'WEBSources/index.html.cc,v'.
       Trying pattern rule with stem 'index.html.cc'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.cc,v'.
       Trying pattern rule with stem 'index.html.cc'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.cc'.
       Trying pattern rule with stem 'index.html.cc'.
       Trying implicit prerequisite 'WEBSources/s.index.html.cc'.
       Trying pattern rule with stem 'index.html.cc'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.cc'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.C'.
      Looking for a rule with intermediate file 'WEBSources/index.html.C'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html.C'.
       Trying implicit prerequisite 'WEBSources/index.html.C,v'.
       Trying pattern rule with stem 'index.html.C'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.C,v'.
       Trying pattern rule with stem 'index.html.C'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.C'.
       Trying pattern rule with stem 'index.html.C'.
       Trying implicit prerequisite 'WEBSources/s.index.html.C'.
       Trying pattern rule with stem 'index.html.C'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.C'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.cpp'.
      Looking for a rule with intermediate file 'WEBSources/index.html.cpp'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html.cpp'.
       Trying implicit prerequisite 'WEBSources/index.html.cpp,v'.
       Trying pattern rule with stem 'index.html.cpp'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.cpp,v'.
       Trying pattern rule with stem 'index.html.cpp'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.cpp'.
       Trying pattern rule with stem 'index.html.cpp'.
       Trying implicit prerequisite 'WEBSources/s.index.html.cpp'.
       Trying pattern rule with stem 'index.html.cpp'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.cpp'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.p'.
      Looking for a rule with intermediate file 'WEBSources/index.html.p'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.web'.
       Trying pattern rule with stem 'index.html.p'.
       Trying implicit prerequisite 'WEBSources/index.html.p,v'.
       Trying pattern rule with stem 'index.html.p'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.p,v'.
       Trying pattern rule with stem 'index.html.p'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.p'.
       Trying pattern rule with stem 'index.html.p'.
       Trying implicit prerequisite 'WEBSources/s.index.html.p'.
       Trying pattern rule with stem 'index.html.p'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.p'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.web'.
       Looking for a rule with intermediate file
'WEBSources/index.html.web'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html.web'.
        Trying implicit prerequisite 'WEBSources/index.html.web,v'.
        Trying pattern rule with stem 'index.html.web'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.web,v'.
        Trying pattern rule with stem 'index.html.web'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.web'.
        Trying pattern rule with stem 'index.html.web'.
        Trying implicit prerequisite 'WEBSources/s.index.html.web'.
        Trying pattern rule with stem 'index.html.web'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.web'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.f'.
      Looking for a rule with intermediate file 'WEBSources/index.html.f'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.F'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.r'.
       Trying pattern rule with stem 'index.html.f'.
       Trying implicit prerequisite 'WEBSources/index.html.f,v'.
       Trying pattern rule with stem 'index.html.f'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.f,v'.
       Trying pattern rule with stem 'index.html.f'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.f'.
       Trying pattern rule with stem 'index.html.f'.
       Trying implicit prerequisite 'WEBSources/s.index.html.f'.
       Trying pattern rule with stem 'index.html.f'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.f'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.F'.
       Looking for a rule with intermediate file 'WEBSources/index.html.F'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html.F'.
        Trying implicit prerequisite 'WEBSources/index.html.F,v'.
        Trying pattern rule with stem 'index.html.F'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.F,v'.
        Trying pattern rule with stem 'index.html.F'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.F'.
        Trying pattern rule with stem 'index.html.F'.
        Trying implicit prerequisite 'WEBSources/s.index.html.F'.
        Trying pattern rule with stem 'index.html.F'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.F'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.r'.
       Looking for a rule with intermediate file 'WEBSources/index.html.r'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html'.
        Rejecting impossible implicit prerequisite
'WEBSources/index.html.l'.
        Trying pattern rule with stem 'index.html.r'.
        Trying implicit prerequisite 'WEBSources/index.html.r,v'.
        Trying pattern rule with stem 'index.html.r'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.r,v'.
        Trying pattern rule with stem 'index.html.r'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.r'.
        Trying pattern rule with stem 'index.html.r'.
        Trying implicit prerequisite 'WEBSources/s.index.html.r'.
        Trying pattern rule with stem 'index.html.r'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.r'.
      Trying pattern rule with stem 'index.html'.
      Rejecting impossible implicit prerequisite 'WEBSources/index.html.F'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.m'.
      Looking for a rule with intermediate file 'WEBSources/index.html.m'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.ym'.
       Trying pattern rule with stem 'index.html.m'.
       Trying implicit prerequisite 'WEBSources/index.html.m,v'.
       Trying pattern rule with stem 'index.html.m'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.m,v'.
       Trying pattern rule with stem 'index.html.m'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.m'.
       Trying pattern rule with stem 'index.html.m'.
       Trying implicit prerequisite 'WEBSources/s.index.html.m'.
       Trying pattern rule with stem 'index.html.m'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.m'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.ym'.
       Looking for a rule with intermediate file 'WEBSources/index.html.ym'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html.ym'.
        Trying implicit prerequisite 'WEBSources/index.html.ym,v'.
        Trying pattern rule with stem 'index.html.ym'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.ym,v'.
        Trying pattern rule with stem 'index.html.ym'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.ym'.
        Trying pattern rule with stem 'index.html.ym'.
        Trying implicit prerequisite 'WEBSources/s.index.html.ym'.
        Trying pattern rule with stem 'index.html.ym'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.ym'.
      Trying pattern rule with stem 'index.html'.
      Rejecting impossible implicit prerequisite 'WEBSources/index.html.r'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.s'.
      Looking for a rule with intermediate file 'WEBSources/index.html.s'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.S'.
       Trying pattern rule with stem 'index.html.s'.
       Trying implicit prerequisite 'WEBSources/index.html.s,v'.
       Trying pattern rule with stem 'index.html.s'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.s,v'.
       Trying pattern rule with stem 'index.html.s'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.s'.
       Trying pattern rule with stem 'index.html.s'.
       Trying implicit prerequisite 'WEBSources/s.index.html.s'.
       Trying pattern rule with stem 'index.html.s'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.s'.
       Trying pattern rule with stem 'index.html'.
       Trying implicit prerequisite 'WEBSources/index.html.S'.
       Looking for a rule with intermediate file 'WEBSources/index.html.S'.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem 'index.html.S'.
        Trying implicit prerequisite 'WEBSources/index.html.S,v'.
        Trying pattern rule with stem 'index.html.S'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.S,v'.
        Trying pattern rule with stem 'index.html.S'.
        Trying implicit prerequisite 'WEBSources/RCS/index.html.S'.
        Trying pattern rule with stem 'index.html.S'.
        Trying implicit prerequisite 'WEBSources/s.index.html.S'.
        Trying pattern rule with stem 'index.html.S'.
        Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.S'.
      Trying pattern rule with stem 'index.html'.
      Rejecting impossible implicit prerequisite 'WEBSources/index.html.S'.
      Trying pattern rule with stem 'index.html'.
      Trying implicit prerequisite 'WEBSources/index.html.mod'.
      Looking for a rule with intermediate file 'WEBSources/index.html.mod'.
       Avoiding implicit rule recursion.
       Avoiding implicit rule recursion.
       Trying pattern rule with stem 'index.html.mod'.
       Trying implicit prerequisite 'WEBSources/index.html.mod,v'.
       Trying pattern rule with stem 'index.html.mod'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.mod,v'.
       Trying pattern rule with stem 'index.html.mod'.
       Trying implicit prerequisite 'WEBSources/RCS/index.html.mod'.
       Trying pattern rule with stem 'index.html.mod'.
       Trying implicit prerequisite 'WEBSources/s.index.html.mod'.
       Trying pattern rule with stem 'index.html.mod'.
       Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.mod'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.c'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.cc'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.C'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.cpp'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.p'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.f'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.F'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.m'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.r'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.s'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.S'.
     Trying pattern rule with stem 'index.html'.
     Rejecting impossible implicit prerequisite 'WEBSources/index.html.mod'.
     Trying pattern rule with stem 'index.html'.
     Trying implicit prerequisite 'WEBSources/index.html.sh'.
     Looking for a rule with intermediate file 'WEBSources/index.html.sh'.
      Avoiding implicit rule recursion.
      Trying pattern rule with stem 'index.html.sh'.
      Trying implicit prerequisite 'WEBSources/index.html.sh,v'.
      Trying pattern rule with stem 'index.html.sh'.
      Trying implicit prerequisite 'WEBSources/RCS/index.html.sh,v'.
      Trying pattern rule with stem 'index.html.sh'.
      Trying implicit prerequisite 'WEBSources/RCS/index.html.sh'.
      Trying pattern rule with stem 'index.html.sh'.
      Trying implicit prerequisite 'WEBSources/s.index.html.sh'.
      Trying pattern rule with stem 'index.html.sh'.
      Trying implicit prerequisite 'WEBSources/SCCS/s.index.html.sh'.
     No implicit rule found for 'WEBSources/index.html'.
     Finished prerequisites of target file 'WEBSources/index.html'.
    Must remake target 'WEBSources/index.html'.
make: *** No rule to make target 'WEBSources/index.html', needed by
'include/pages/index.html.h'.  Stop.

Op za 2 dec 2023 om 19:45 schreef Olaf ***@***.***>:

**Comment by Kolkman** [comment]
I am at a loss, you said  `WEBSources/index.html` is an existing file and still make is looking for it.

Does
`ls -l  WEBSources/index.html` produce a sensible result?

**Comment by hooijschuur** [comment]
[image: afbeelding.png]web
is see WEBSources and WEBsources ?
tried to change it WEBSources >> WEBsources in the makefile with no succes.

is it possible to get a local copy instead of github.
i don,t know if it makes a difference but ?

Op ma 4 dec 2023 om 08:31 schreef Olaf ***@***.***>:

**Comment by Kolkman** [comment]
I'll correct the case in the Makefile later, I develop on a Mac with a case insensitive filesystem and had not spotted that bug yet. 

Here it is compressed since I cannot upload html to github's interface
[index.html.zip](https://github.com/Kolkman/ESP32ressoMachine/files/13545539/index.html.zip)
Here you also find the compressed include/pages directory, the output of the make process.
[pages.zip](https://github.com/Kolkman/ESP32ressoMachine/files/13545555/pages.zip)
